### ISSUE TITLE
Can't save the obj file!!About the pytorch version 

### ISSUE THREAD

**Issue by Lixz123456** [facebookresearch/pifuhd#10]
when I run the test code,I found the  visualization result can be saved,,but the obj can not be saved.this is the screenshot.help me
![image](https://user-images.githubusercontent.com/47596395/84865324-9a6d3a80-b0aa-11ea-93f0-3ffd62d74f94.png)

**Comment by shunsukesaito** [comment]
Seems that you use older version of pytorch. Please make sure you use the latest version of pytorch.

**Comment by Lixz123456** [comment]
I use the 1.1.0 for pytorch,I don't know why.
Are there any requirements for CUDA versions?

**Comment by shunsukesaito** [comment]
Indeed 1.1.0 is outdated. Please update to the latest (I confirmed it works with 1.4.0 or 1.5.0). I don't think specific CUDA version is required as long as pytorch itself is latest.

**Comment by Lixz123456** [comment]
thanks you,I have already sloved this problem.as you say,this code works with pytorch 1.4 or 1.5.
but the Requirement about the pytorch is wrong
![image](https://user-images.githubusercontent.com/47596395/84921456-17be9c80-b0f7-11ea-820e-882d79673c82.png)

**Comment by shunsukesaito** [comment]
Indeed that was not correct. Thanks for pointing it out. I already fixed it!
