### ISSUE TITLE
Google Colab notebook does not work with an error.

### ISSUE THREAD

**Issue by cedro3** [facebookresearch/pifuhd#100]
Google Colab notebook does not work with an error. When I try to move the second Render the result block, I get the following error:

ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

**Comment by PWhiddy** [comment]
According to this https://github.com/facebookresearch/pytorch3d/issues/476

This error may be because the latest version of pytorch3d is only built for pytorch 1.6, while the latest version running is 1.7

I've tried downgrading pytorch to 1.6 but then I see a cuda driver error.

**Comment by PWhiddy** [comment]
Answer is here in previous issue actually if you look
https://github.com/facebookresearch/pifuhd/issues/77#issuecomment-725247401

**Comment by cedro3** [comment]
First run the code below.
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install pytorch3d

Now Google Colab is now working properly.
This issue has been resolved.
Thanks！

**Comment by cedro3** [comment]
First run the code below.
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

Google Colab is now working properly.
This issue has been resolved.
Thanks！

**Comment by cedro3** [comment]
This issue has been resolved.
