### ISSUE TITLE
How to generate 3D models from pictures

### ISSUE THREAD

**Issue by WJinhai** [facebookresearch/pifuhd#102]
Hello， I use this command  “python -m apps.simple_test”  to generate two picture is front and back. 
![image](https://user-images.githubusercontent.com/29060221/102762353-20986f80-43b3-11eb-9999-a454811d6137.png)
How to become the  three-dimensional image in the README?

**Comment by hfarhidzadeh** [comment]
@WJinhai read the instruction, and watch this https://www.youtube.com/watch?v=zzgCoyYyuN0&ab_channel=bycloudump
