### ISSUE TITLE
TypeError: group_keypoints() got an unexpected keyword argument 'demo'

### ISSUE THREAD

**Issue by sxstone** [facebookresearch/pifuhd#103]
I try to run the demo on Google collab, but the following errors always appear. All processes are carried out according to the video, and the input image is also used test.png Why do the following errors occur? After trying many solutions, I don't know if anyone has the same problem. Can it be solved?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-736a0682666b> in <module>()
      3 load_state(net, checkpoint)
      4 
----> 5 get_rect(net.cuda(), [image_path], 512)

<ipython-input-10-2dd51ed5e564> in get_rect(net, images, height_size)
     28             total_keypoints_num += extract_keypoints(heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
     29 
---> 30         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
     31         for kpt_id in range(all_keypoints.shape[0]):
     32             all_keypoints[kpt_id, 0] = (all_keypoints[kpt_id, 0] * stride / upsample_ratio - pad[1]) / scale

TypeError: group_keypoints() got an unexpected keyword argument 'demo'

**Comment by dickkky** [comment]
Same problem.

**Comment by gormonn** [comment]
the same problem:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-736a0682666b> in <module>()
      3 load_state(net, checkpoint)
      4 
----> 5 get_rect(net.cuda(), [image_path], 512)

<ipython-input-23-2dd51ed5e564> in get_rect(net, images, height_size)
     28             total_keypoints_num += extract_keypoints(heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
     29 
---> 30         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
     31         for kpt_id in range(all_keypoints.shape[0]):
     32             all_keypoints[kpt_id, 0] = (all_keypoints[kpt_id, 0] * stride / upsample_ratio - pad[1]) / scale

TypeError: group_keypoints() got an unexpected keyword argument 'demo'`

**Comment by rdelrosa2000** [comment]
I have the same problem. I’ve been trying it for the past 3 days since Sunday and I’m gettin the same error message.

**Comment by kuritaTD** [comment]
I have error that is like below... I don't know how to solve this error.. 
Please teach me how to solve this error...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-736a0682666b> in <module>()
      3 load_state(net, checkpoint)
      4 
----> 5 get_rect(net.cuda(), [image_path], 512)

<ipython-input-11-2dd51ed5e564> in get_rect(net, images, height_size)
     28             total_keypoints_num += extract_keypoints(heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
     29 
---> 30         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
     31         for kpt_id in range(all_keypoints.shape[0]):
     32             all_keypoints[kpt_id, 0] = (all_keypoints[kpt_id, 0] * stride / upsample_ratio - pad[1]) / scale

TypeError: group_keypoints() got an unexpected keyword argument 'demo'

**Comment by shackhorn** [comment]
Same issue!! Glad I'm not alone!

**Comment by MangoDev232** [comment]
Same Error since yesterday. Like 20 hours ago.

**Comment by knicholes** [comment]
The error is stating that the function is received an unexpected keyword argument named "demo."  To get past this problem, stop passing the demo keyword argument to the `group_keypoints` function.

**Comment by sxstone** [comment]
> The error is stating that the function is receiving an unexpected keyword argument named "demo." To get past this problem, stop passing the demo keyword argument to the `group_keypoints` function.

Thank you for your reply. I did the same thing, that is, I deleted the demo keyword, but I don't know if it will bring other effects.

**Comment by EnricoBeltramo** [comment]
Same issue

**Comment by knicholes** [comment]
> > The error is stating that the function is receiving an unexpected keyword argument named "demo." To get past this problem, stop passing the demo keyword argument to the `group_keypoints` function.
> 
> Thank you for your reply. I did the same thing, that is, I deleted the demo keyword, but I don't know if it will bring other effects.

Well, I just tried removing that keyword param, and my results were decent. *shrug*  I guess we'd have to look into the code to see what that keyword does.  Maybe that's why you asked here and not a direct message to me. ;)  Good luck.

**Comment by 0692abhishek** [comment]
same issue plzz give some solution

**Comment by soheilpaper** [comment]
Please remove the demo=True from this part of code:
```
        pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)

```
![image](https://user-images.githubusercontent.com/6679151/103104122-ada12a00-463a-11eb-8a24-212dc4f1f88f.png)


Also you can see the fixed code here:
[https://colab.research.google.com/drive/1YZfHcLDJwRo-8Ty3tV1h0rN7iwrOmftT?usp=sharing](https://colab.research.google.com/drive/1YZfHcLDJwRo-8Ty3tV1h0rN7iwrOmftT?usp=sharing
)

**Comment by shackhorn** [comment]
Alright, but for some reason I am having this error: 
`Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0% 0/1 [00:00<?, ?it/s]/content/pifuhd/lib/data/EvalDataset.py:87: UserWarning: loadtxt: Empty input file: "/content/pifuhd/sample_images/shackcomm2tp_rect.txt"
  rects = np.loadtxt(rect_path, dtype=np.int32)
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/pifuhd/apps/simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "/content/pifuhd/apps/recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "/content/pifuhd/apps/recon.py", line 205, in recon
    test_data = test_dataset[i]
  File "/content/pifuhd/lib/data/EvalDataset.py", line 131, in __getitem__
    return self.get_item(index)
  File "/content/pifuhd/lib/data/EvalDataset.py", line 93, in get_item
    im = crop_image(im, rect)
  File "/content/pifuhd/lib/data/EvalDataset.py", line 17, in crop_image
    x, y, w, h = rect
ValueError: not enough values to unpack (expected 4, got 0)`

The `xxxxx_rect.txt` file doesn't seem to be generating properly, as I have had no luck with it. Is this related to removing `demo=True`?

**Comment by rdelrosa2000** [comment]
> Please remove the demo=True from this part of code:
> 
> ```
>         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
> ```
> 
> ![image](https://user-images.githubusercontent.com/6679151/103104122-ada12a00-463a-11eb-8a24-212dc4f1f88f.png)
> 
> Also you can see the fixed code here:
> https://colab.research.google.com/drive/1YZfHcLDJwRo-8Ty3tV1h0rN7iwrOmftT?usp=sharing

**Comment by rdelrosa2000** [comment]
> Please remove the demo=True from this part of code:
> 
> ```
>         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
> ```
> 
> ![image](https://user-images.githubusercontent.com/6679151/103104122-ada12a00-463a-11eb-8a24-212dc4f1f88f.png)
> 
> Also you can see the fixed code here:
> https://colab.research.google.com/drive/1YZfHcLDJwRo-8Ty3tV1h0rN7iwrOmftT?usp=sharing

Thank you for providing the fixed code. It worked for me the first time, but my subsequent tries failed with the usual error message.

**Comment by CubeBag** [comment]
Same, my `_rect.txt` file is empty

**Comment by HenrikoMagnifico** [comment]
Same error

**Comment by shunsukesaito** [comment]
You can remove demo argument in group_keypoints(). I have removed it in the released colab notebook. 
For those who experience empty rect file, likely no keypoint is detected in an input image. Feel free to post failure images here if you need further diagnosis.

**Comment by ahmedaisar** [comment]
Why is this closed when the problem is NOT FIXED??

**Comment by ahmedaisar** [comment]
We are still getting EMPTY rect_files

**Comment by mavericayman** [comment]
Can anyone help me solve the blank _rect file generated?

Actually on the fixed colab sheet it seems to just get stuck somewhere and it never finishes on the get_rect(net.cuda(), [image_path], 512) line

**Comment by davidbernat** [comment]
The `_rect.txt` file contains a bounding box which isolates the person in the image. 

1. The full-pipeline `_rext.txt` is generated by first using the openpose.py script to generate an OpenPose wireframe of each individual. OpenPose stores its results in an `.obj` file. Then, the PiFUHD script uses the OpenPose `.obj` file to generate the bounding box internally which it then stores in the `_rect.txt`. Alternatively, instead of using OpenPose, one can simply supply the `_rect.txt`. Presumably, if you do not have a bounding box you can set the bounding box to be the full dimensions of the image.
2. Unfortunately, I do not know the format for the `_rect.txt` so I cannot help you write one by hand. If anyone has that information, and can post a sample file, please do. When I generate one I will post it here.

**Comment by ricardo7k** [comment]
Just change the last code before the cell with erro to use int instead of np.int, and change the np.bool from pifuhd/lib/sdf.py to use bool
