### ISSUE TITLE
Excustion Issue

### ISSUE THREAD

**Issue by sonyxo2** [facebookresearch/pifuhd#104]
net = PoseEstimationWithMobileNet()
checkpoint = torch.load('checkpoint_iter_370000.pth', map_location='cpu')
load_state(net, checkpoint)

get_rect(net.cuda(), [image_path], 512)

TypeError                                 Traceback (most recent call last)
<ipython-input-8-736a0682666b> in <module>()
      3 load_state(net, checkpoint)
      4 
----> 5 get_rect(net.cuda(), [image_path], 512)

<ipython-input-7-2dd51ed5e564> in get_rect(net, images, height_size)
     28             total_keypoints_num += extract_keypoints(heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
     29 
---> 30         pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, pafs, demo=True)
     31         for kpt_id in range(all_keypoints.shape[0]):
     32             all_keypoints[kpt_id, 0] = (all_keypoints[kpt_id, 0] * stride / upsample_ratio - pad[1]) / scale

TypeError: group_keypoints() got an unexpected keyword argument 'demo'

**Comment by vj-abishek** [comment]
https://github.com/facebookresearch/pifuhd/issues/103#issue-772654610

**Comment by vj-abishek** [comment]
https://github.com/facebookresearch/pifuhd/issues/103#issue-772654610
