### ISSUE TITLE
error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'

### ISSUE THREAD

**Issue by ljq2020** [facebookresearch/pifuhd#106]
Hi,
When I run `sh ./scripts/demo.sh`, I met this problem:

Compilation failure for vertex shader:
b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Compilation failure for fragment shader:
b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Linker failure: 
b'error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/Documents/HD/apps/render_turntable.py", line 69, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "/home/ubuntu/Documents/HD/lib/render/gl/color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "/home/ubuntu/Documents/HD/lib/render/gl/cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "/home/ubuntu/Documents/HD/lib/render/gl/render.py", line 72, in __init__
    self.model_mat_unif = glGetUniformLocation(self.program, 'ModelMat')
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/ubuntu/anaconda3/envs/HD/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (3, b'ModelMat\x00'),
	result = -1
)
Segmentation fault (core dumped)

System:
OS: Ubuntu 18.04
Python version: 3.8.5
PyTorch version: 1.7.1
Torchvision version: 0.8.2
cudatoolkit 11.0.221
GPU: RTX3080

**Comment by mrahsanahmad** [comment]
run in ur terminal
export MESA_GL_VERSION_OVERRIDE=3.3

this should solve the prblm

**Comment by ljq2020** [comment]
Thanks a lot, the problem has been solved.

**Comment by fengchuiguo1994** [comment]
hi, when I run export MESA_GL_VERSION_OVERRIDE=3.3.
a new error:
ShaderCompilationError: ("Shader compile failure (0): b'0:2(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES\\n'", [b'\n\t\t\t\t\t\t#version 430 core\n\n\t\t\t\t\t\tlayout(location = 0) in vec3 position;\n\t\t\t\t\tlayout(location = 1) in vec3 normal;\n\t\t\t\t\tlayout (location = 2) in vec3 vertexcolor;\n\t\t\t\t\tlayout (location = 3) in vec2 texcoord;\n\n\t\t\t\t\tuniform mat4 model;\n\t\t\t\t\tuniform mat4 view;\n\t\t\t\t\tuniform mat4 projection;\n\t\t\t\t\tuniform vec3 color;\n\t\t\t\t\tuniform vec4 clip_plane ;\n\t\t\t\t\tuniform int isVertexcolor;\n\n\t\t\t\t\tout vec3 tnorm;\n\t\t\t\t\tout vec3 light;\n\t\t\t\t\tout vec3 view_direction;\n\t\t\t\t\tout vec3 vertcolor;\n\t\t\t\t\tout vec2 v_texture;\n\t\t\t\t\tout float depth;\n\t\t\t\t\tvoid main(void) {\n\t\t\t\t\t\tgl_ClipDistance[0] = dot(vec4(position,1.0), clip_plane);\n\t\t\t\t\t\tlight = normalize( vec4(0.0, 0.0, 1.0,1.0)).xyz;\n\t\t\t\t\t\tvec4 pos_in_camera = view*model * vec4(position.xyz, 1.0);\n\t\t\t\t\t\tgl_Position = projection* pos_in_camera;\n\t\t\t\t\t\ttnorm = normalize((view*model*vec4(normal.xyz, 0.0)).xyz);\n\t\t\t\t\t\t//tnorm = vNormal.xyz;\n\t\t\t\t\t\tview_direction = normalize(pos_in_camera.xyz);\n\t\t\t\t\t\tvertcolor = color;\n\t\t\t\t\t\tif (isVertexcolor>0)\n\t\t\t\t\t\t\tvertcolor =vertexcolor;\n\t\t\t\t\t\telse\n\t\t\t\t\t\t\tvertcolor = color;\n\t\t\t\t\t\tv_texture = texcoord;\n\t\t\t\t\t}\n\t\t\t\t\t'], GL_VERTEX_SHADER)
