### ISSUE TITLE
Is there an easy way to generate a depth map?

### ISSUE THREAD

**Issue by nosy-b** [facebookresearch/pifuhd#109]
As we get the Normal Map as output png, could we also get a png with the DepthMap?

Thanks!

**Comment by nosy-b** [comment]
Ok I added a function in render_turntable.py to output Depth instead of normals :) I guess I could compute it earlier without the need to generate the mesh which takes a long time...
![piFuHDWithDepthjpg](https://user-images.githubusercontent.com/158514/107147700-b716f500-694f-11eb-86fa-88ce30c616cd.jpg)

**Comment by sandorkonya** [comment]
@nosy-b ,
i am looking for the same output (depth map) and I found the code for generating normals in the mesh.py, https://github.com/facebookresearch/pifuhd/blob/ee51fc23629c4afc99dbfd235c5b8bbd77a86aa2/lib/render/mesh.py#L303
but is there a function for generating depth maps, seems not to be in there.
Would you mind sharing your solution if it's not proprietary or the way to solve this, please?

Thank you in advance!

**Comment by sanazsab** [comment]
It is also the same question from my side for 
but is there a function for generating depth maps, seems not to be in there.

Have you found sth for that?

**Comment by sandorkonya** [comment]
@sanazsab nope.

**Comment by lql1233** [comment]
> 好的，我在 render_turntable.py 中添加了一个函数来输出深度而不是法线:) 我想我可以更早地计算它而无需生成需要很长时间的网格...... ![piFuHDWithDepthjpg](https://user-images.githubusercontent.com/158514/107147700-b716f500-694f-11eb-86fa-88ce30c616cd.jpg)

Did you use the get_value function? How did you use it? My problem is that I need the sample.vs file, but I don't know what this file is? How did you do it?
