### ISSUE TITLE
openpose on windows

### ISSUE THREAD

**Issue by Maxinger15** [facebookresearch/pifuhd#12]
Which file from the openpose binaries should I use on Windows10? The file (./build/examples/openpose/openpose.bin) given in batch_openpose.py does not exist on the Windows 10 binaries with the openpose version 1.6.0

Btw:. In the documentation the command (python apps/process_openpose.py .....) is wrong.
It has to be (python apps/batch_openpose.py .....) i guess.

**Comment by shunsukesaito** [comment]
I'm afraid I don't know answer to openpose related question. You may as well ask in openpose community. 

Alternatively, we provide a light-weight way to get cropping rectangle on google colab demo. Please take a look. The quality of cropping should be roughly same. 
https://colab.research.google.com/drive/11z58bl3meSzo6kFqkahMa35G5jmh2Wgt?usp=sharing

**Comment by shunsukesaito** [comment]
I'll fix readme as well. Thanks for pointing it out!!

**Comment by Maxinger15** [comment]
Can you give me a small description what the batch_openpose.py does exactly (what are joints and for what are they needed in the image cropping process?) that I have a base for my research.

**Comment by shunsukesaito** [comment]
Joints are stored as json file following BODY_25 in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md .
As some of input images lack legs in the image, I made a small script to get consistent cropping of input image to be fed into PIFuHD. Optionally you can directly specify what bounding you want to use. Please check out the colab demo on how to use this option.

**Comment by jeesunkim** [comment]
@maxinger15 
Openpose portable version for windows here - https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases
Select openpose-1.6.0-binaries-win64-gpu-python-flir-3d_recommended.zip (if you have a gpu)
Unzip
Under the bin folder you'll find OpenPoseDemo.exe
OpenPoseDemo.exe
Now put your test png file in a new folder under the Openpose root directory, e.g., C:\openpose-1.6.0\openpose\examples\media\test\test.png - make sure it is the only png file in that folder
then open a windows command window - and naviagate to the openpose root dir and issue this command
bin\OpenPoseDemo.exe --image_dir examples\media\test\test.png --face --hand --write_json output/
This will create a test_keypoints.json file - this is what you use with pifuhd...

**Comment by gormonn** [comment]
For windows, just repace this code in `batch_openpose.py`:
```
cmd = "cd {0}; ./build/examples/openpose/openpose.bin --image_dir {1} --write_json {2} --render_pose 2 --face --face_render 2 --hand --hand_render 2".format(op_dir, input_path, out_json_path)
```
to:
```
cmd = "cd {0} && .\\bin\\OpenPoseDemo.exe --image_dir {1} --write_json {2} --render_pose 2 --face --face_render 2 --hand --hand_render 2".format(op_dir, input_path, out_json_path)
```
