### ISSUE TITLE
Is it possible to retain the original color of the photo we are providing as an input?

### ISSUE THREAD

**Issue by desmondblue** [facebookresearch/pifuhd#122]
Upon reconstructing the model the original color of the picture is not retained is it possible to retain the color in the reconstructed model?

for example: for this picture the color of the image is green black but the output model is reconstructed in a purplish blue gradient
![result_test_512](https://user-images.githubusercontent.com/24765695/118393320-322d2d00-b65c-11eb-92f1-46af340976bf.png)

**Comment by manncodes** [comment]
The output of pifuHD model is just an .obj file, to render color(or to be more presice the surface of 3D object) you'll require a material file (.mtl).

Check this for futher info for making mtl file from obj file.
https://blender.stackexchange.com/questions/127996/how-to-make-a-mtl-file-from-obj-file/146184
