### ISSUE TITLE
demo.sh gives error OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit

### ISSUE THREAD

**Issue by heikog** [facebookresearch/pifuhd#128]
`
Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0%|                                                                                                       | 0/1 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_test_512.obj
Killed
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/pifuhd/apps/render_turntable.py", line 69, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "/opt/pifuhd/lib/render/gl/color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "/opt/pifuhd/lib/render/gl/cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "/opt/pifuhd/lib/render/gl/render.py", line 41, in __init__
    glutInit()
  File "/home/kali/.local/lib/python3.9/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/kali/.local/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

`

**Comment by witwave** [comment]
Hi heikog, I have the same error, how did you fix it?

**Comment by witwave** [comment]
> ` Resuming from ./checkpoints/pifuhd.pt Warning: opt is overwritten. test data size: 1 initialize network with normal initialize network with normal generate mesh (test) ... 0%| | 0/1 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_test_512.obj Killed Traceback (most recent call last): File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/opt/pifuhd/apps/render_turntable.py", line 69, in renderer = ColorRender(width=args.width, height=args.height) File "/opt/pifuhd/lib/render/gl/color_render.py", line 34, in **init** CamRender.**init**(self, width, height, name, program_files=program_files) File "/opt/pifuhd/lib/render/gl/cam_render.py", line 32, in **init** Render.**init**(self, width, height, name, program_files, color_size, ms_rate) File "/opt/pifuhd/lib/render/gl/render.py", line 41, in **init** glutInit() File "/home/kali/.local/lib/python3.9/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit _base_glutInit( ctypes.byref(count), holder ) File "/home/kali/.local/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 423, in **call** raise error.NullFunctionError( OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
> 
> `
Hi heikog, I have the same error, how did you fix it?

**Comment by AndrewMorgan2** [comment]
I did this :
sudo apt-get install freeglut3-dev
But now I get:
Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0%|                                                                                                                   | 0/1 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_test_512.obj
Killed
[]
