### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by alitokur** [facebookresearch/pifuhd#14]
hi, can we give input as a .mp4?

**Comment by shunsukesaito** [comment]
If you want to process video frames, you need to first convert it into a collection of frames using ffmpeg or so. Then process each image individually.

**Comment by alitokur** [comment]
thank you sir, and can i ask you one more thing? how can i use Multi-view PIFu. i couldn't see any parameters for that.

**Comment by shunsukesaito** [comment]
Unfortunately, this repository does not provide multi-view integration function. However, you could modify this code base by following the multi-view integration scheme the original PIFu work presents for your needs.

**Comment by alitokur** [comment]
Thank you Sir, sincerely yours.
