### ISSUE TITLE
What should I do if I want to test a new picture?

### ISSUE THREAD

**Issue by ww5171351** [facebookresearch/pifuhd#146]
Thank you for your work and answers. What should I do if I want to test a new picture? How did test_keypoints.json get this file? Thank you for your answer, it is very important to me.

**Comment by satsubatsu347** [comment]
1. Put a new picture or series of pictures in the "sample_images" folder.

2. Run this command to generate a .JSON for corresponding image(s) in "sample_images" folder.
(Read Issue #134 for additional instructions on this step):
python apps/batch_openpose.py -d {openpose_folder} -i {path_of_input} -o {path_of_out}

3. After that is done, run this command, and go do something else for a while:
python -m apps.simple_test -i {path_of_input} -o {path_of_output}

4. (Optional) Run this to clean up generated OBJ(s) (This overwrites original OBJs. Backup models first):
python apps/clean_mesh.py -f {path_of_objs}

Good luck with your project!

**Comment by ww5171351** [comment]
Thank you for your answer.
