### ISSUE TITLE
error cannot marching cubes (on CPU)

### ISSUE THREAD

**Issue by fatihmtlm** [facebookresearch/pifuhd#149]
I've 6GB RTX 3060 laptop GPU and it is not enough. So I want to use my CPU instead but I get this error with the test image:

**Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0%|                                                                                      | 0/1 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_test_200.obj   
error cannot marching cubes
cannot unpack non-iterable int object
100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [00:19<00:00, 19.62s/it]**

How can I solve this problem?

**Comment by VisionaryMind** [comment]
You likely have a newer version of `scikit-image` installed, which does not implement `marching_cubes_lewiner`. If you will change line 77 of lib.mesh_util from `marching_cubes_lewiner` to simple `marching_cubes`, you will likely be able to get around this problem (if, in fact, the issue is your scikit-image package). I have 0.18.3, for example, and I had to implement this change.

**Comment by fatihmtlm** [comment]
Thank you, the problem is solved

**Comment by Danial-Kord** [comment]
> You likely have a newer version of `scikit-image` installed, which does not implement `marching_cubes_lewiner`. If you will change line 77 of lib.mesh_util from `marching_cubes_lewiner` to simple `marching_cubes`, you will probably be able to get around this problem (if, in fact, the issue is your scikit-image package). I have 0.18.3, for example, and I had to implement this change.

Hey man, I had the same problem and changing that line cause me another one with the details on below:
error message --> "need at least one array to concatenate"
happens in line 56 of recon.py while trying to execute --> save_img = np.concatenate(save_img_list, axis=1)
any idea how to fix this?

**Comment by yunfan258** [comment]
“verts, faces, normals, values = measure.marching_cubes(sdf, 0.5)“
line45，it works
