### ISSUE TITLE
No module named apps!

### ISSUE THREAD

**Issue by dduartee** [facebookresearch/pifuhd#16]
hello, when I execute the command
`sh ./scripts/demo.sh`
it appears the error
`/usr/bin/python: No module named apps`

I reviewed all the documentation, but it did not work
Any idea how to solve it?

**Comment by shunsukesaito** [comment]
Please check if you use Python 3.6 or above. I previously had the same issue when trying to run the code with Python 2.x

**Comment by dduartee** [comment]
Thank you!
I was actually running on `python2.7`
I will use `python3`
