### ISSUE TITLE
The google colab stopped working even after trying the different pytorch 3D installs 

### ISSUE THREAD

**Issue by PIETERJANAHENKONA** [facebookresearch/pifuhd#177]
I'm not shure how to use this anymore.

**Comment by sicker2022** [comment]
This is because the cuda version of colab has been updated to 11.6.

**Comment by shunsukesaito** [comment]
The error should be fixed now. Please let me know if the error persists. I'll close the issue for now. But feel free to reopen.

**Comment by Muhammad1umer-tech** [comment]
I'm getting this error while running in colab

ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d
