### ISSUE TITLE
Empty results file

### ISSUE THREAD

**Issue by RocketbunnyDev** [facebookresearch/pifuhd#180]
I have followed all the steps from this video: https://www.youtube.com/watch?v=QANxO69y6r4
But after having the **pifuhd** file appear and the **lightweight-human-pose estimation** file appear, the results file was empty and just had the recon file. 
I had no errors when running, but this somehow happened.
Any help would be appreciated.

**Comment by shunsukesaito** [comment]
The error should be fixed now. Please let me know if the error persists. I'll close the issue for now. But feel free to reopen.
