### ISSUE TITLE
No module named 'pytorch3d'

### ISSUE THREAD

**Issue by OIiveTree** [facebookresearch/pifuhd#183]

**Comment by shunsukesaito** [comment]
The error should be fixed now. Please let me know if the error persists. I'll close the issue for now. But feel free to reopen.

**Comment by mikeglopez** [comment]
Seem to be having this issue again:

from the "Render the result" section errors:

ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d

**Comment by ICELORD937** [comment]
version_str = 'py310_cu118_pyt201'
!pip install fvcore iopath
!pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
