### ISSUE TITLE
Run PIFuHD! : error cannot marching cubes cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by gusfed** [facebookresearch/pifuhd#185]
![image](https://user-images.githubusercontent.com/128433115/226485563-06585240-4cee-4d32-9fed-ad094ca81ff6.png)
 
Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  2
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0% 0/2 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_Homeralpha2_256.obj
error cannot marching cubes
cannot unpack non-iterable int object
 50% 1/2 [00:08<00:08,  8.49s/it]./results/pifuhd_final/recon/result_test_256.obj
error cannot marching cubes
cannot unpack non-iterable int object
100% 2/2 [00:13<00:00,  6.67s/it]

**Comment by MalignusCN** [comment]
> ![image](https://user-images.githubusercontent.com/128433115/226485563-06585240-4cee-4d32-9fed-ad094ca81ff6.png)
> 
> Resuming from ./checkpoints/pifuhd.pt Warning: opt is overwritten. test data size: 2 initialize network with normal initialize network with normal generate mesh (test) ... 0% 0/2 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_Homeralpha2_256.obj error cannot marching cubes cannot unpack non-iterable int object 50% 1/2 [00:08<00:08, 8.49s/it]./results/pifuhd_final/recon/result_test_256.obj error cannot marching cubes cannot unpack non-iterable int object 100% 2/2 [00:13<00:00, 6.67s/it]

You can follow the reply from https://github.com/facebookresearch/pifuhd/issues/85#issuecomment-1336467047, which is useful for me~

**Comment by shunsukesaito** [comment]
The error should be fixed now. Please let me know if the error persists. I'll close the issue for now. But feel free to reopen.
