### ISSUE TITLE
no result.

### ISSUE THREAD

**Issue by FreseIlias** [facebookresearch/pifuhd#187]
Good afternoon.
I wanted to convert the ded.png image to 3D. but there is an error. The error is in the screenshot. What is it and how to fix it?
![ded](https://user-images.githubusercontent.com/122466021/227720958-3957808b-02ba-48b1-bd16-1081b2af818d.png)
![ShooterScreenshot-1069-25-03-23](https://user-images.githubusercontent.com/122466021/227720972-356a7e89-230f-496d-baf4-062f4fb7a9fb.png)

**Comment by shunsukesaito** [comment]
The error should be fixed now. Please let me know if the error persists. I'll close the issue for now. But feel free to reopen.

**Comment by FreseIlias** [comment]
Thank you. I checked everything is working

вс, 26 мар. 2023 г. в 17:21, Shunsuke Saito ***@***.***>:
