### ISSUE TITLE
Is there a step by step instruction on how to run this in windows offline ?

### ISSUE THREAD

**Issue by BracerJack** [facebookresearch/pifuhd#23]

**Comment by SomeAB** [comment]
Agree with Bracer, dear devs please provide a demo that can be run on a windows10 device with few simple steps, since google collab has a maximum resolution limit of 256. Thus a person can test your model at 1024 res.

**Comment by tushgaurav** [comment]
You need the following packages installed on your computer to run this.
PyTorch, son, PIL, skimage, tqdm, numpy, cv2
After this follow the steps provided in the PIFuHD Demo.

**Comment by benknight135** [comment]
I have [forked](https://github.com/benknight135/pifuhd.git) this repository and added scripts for installing and running this on Windows. This should make installing on Windows very simple.
