### ISSUE TITLE
I want to ask, How to use a single photo to generate the texture map of the model?

### ISSUE THREAD

**Issue by EdenShadow** [facebookresearch/pifuhd#25]
How to generate this texture？

**Comment by shunsukesaito** [comment]
To be clear, this PIFuHD repository does not provide texture inference module in contrast to pifu repository (https://github.com/shunsukesaito/PIFu). The default output is colored by surface normal.

**Comment by EdenShadow** [comment]
thanks，@shunsukesaito
Is there any recommended method for texture inference module?

**Comment by shunsukesaito** [comment]
You can take a look at the PIFu repository link above. As far as I know, this is the only open-sourced texture inference system out there from a single image.

**Comment by AIdeveloper-oz** [comment]
> You can take a look at the PIFu repository link above. As far as I know, this is the only open-sourced texture inference system out there from a single image.

Yes. this is the only open sourced texture inference system, but still it would be helpful if the multi-view process is explained in depth. I tried by changing the number of views, as explained in the paper. Either it creates individual model for each pose(view) or quits execution to throw error.

**Comment by shunsukesaito** [comment]
Please open an issue in the PIFu repository, not here for anything related to the original work of PIFu.

**Comment by dardo82** [comment]
Please implement texture generation for the HD version, it they were available in the standard version it was for good reasons.
