### ISSUE TITLE
Training source code

### ISSUE THREAD

**Issue by doantientai** [facebookresearch/pifuhd#29]
Congratulations on your great work!

If I want to train PihuHD on another 3d dataset, where should I start? I couldn't find an instruction on how to train the model. Perhaps it is not released yet?

Thank you very much!

**Comment by BaldrLector** [comment]
+1, waiting for the release of the training code.

**Comment by shunsukesaito** [comment]
We may not be able to release training code near future. However, all the training details are described in the published paper: https://arxiv.org/pdf/2004.00452.pdf.
As @BaldrLector mentions, the PIFu repository provides a data generation code which uses the identical algorithm to the data generation in PIFuHD. Also the training code in PIFu can be repurposed for PIFuHD with small modifications.

**Comment by doantientai** [comment]
Thank you!
