### ISSUE TITLE
how was the  Pre-trained data genererated?

### ISSUE THREAD

**Issue by daxbo** [facebookresearch/pifuhd#30]
Hello, 
I'm curious about how the Pre Trained data was generated.
I know you've used render-people models to train the model.

regards.

**Comment by shunsukesaito** [comment]
Data generation algorithm is identical to how PIFu training data is generated (but image resolution in PIFuHD is 1024x1024). You can find the code here https://github.com/shunsukesaito/PIFu#data-generation-linux-only
