### ISSUE TITLE
hand-painted character

### ISSUE THREAD

**Issue by stone100010** [facebookresearch/pifuhd#32]
I want to use a better hand-painted character to generate 3D model, please tell me how to do it, thank you!

**Comment by stone100010** [comment]
![writ](https://user-images.githubusercontent.com/48286567/87383556-24d28c80-c5cc-11ea-84c2-9de13b35f6fa.png)

**Comment by BaldrLector** [comment]
@stone100010  hi, you need to  first align the image with keypoints (use openpose) to get *_keypoints.json file.
See the **Testing** section.

**Comment by stone100010** [comment]
I have used " colab demo " about this picture,but it's not good,then i think your deeplearning model is very useful for person photo.so i want  to change deeplearning model with a new style dataset,can you help me ?

**Comment by shunsukesaito** [comment]
Please refer to #29 for training with your own data.
