### ISSUE TITLE
Testing with perspective camera mode failed

### ISSUE THREAD

**Issue by ChenFengYe** [facebookresearch/pifuhd#34]
After downloading the provided testing model, I run both orthogonal and perspective camera mode with 
`sh ./scripts/demo.sh`
I change this camera mode by modifying apps/recon.py line 168-170:

>     if use_rect:
>        test_dataset = EvalDataset(opt)
>     else:
>        test_dataset = EvalWPoseDataset(opt)

to

>     if use_rect:
>        test_dataset = EvalDataset(opt, 'perspective')
>     else:
>        test_dataset = EvalWPoseDataset(opt, 'perspective')

However, the results of orthogonal mode look great, but the results of perspective mode failed like below:
![image](https://user-images.githubusercontent.com/16475892/87426503-d5af4a80-c611-11ea-92d9-46914d1c2f35.png)
I output the value of calib data in lib/data/EvalWposeDataset.py - line 270
> calib_data = {'proj':projection_matrix, 'instr':intrinsic}
> proj =
     1     0     0     0
     0    -1     0     0
     0     0     1     0
     0     0     0     1

> instr =
   1.084745762711864                                  0                                  0   0.190677966101695
                                  0   1.084745762711864                                  0   0.025423728813559
                                  0                                  0   1.084745762711864                                  0
                                  0                                  0                                  0   1.000000000000000

Do you have any idea to fix this problem? Does it related to this instr matrix?
Look forward to your early reply. Thanks!

**Comment by shunsukesaito** [comment]
The released model is trained with orthogonal projection and you cannot use perspective projection during only testing due to the inconsistency in depth values.

**Comment by ChenFengYe** [comment]
@shunsukesaito Hi, thanks for your quick reply. Good to know it's not a bug or configuration problem. Is it possible to release a model trained with perspective projection? Btw, it has really fantastic results, even testing on my own data. Hope to know more about the model with perspective projection. I guess the FOV/focus length might affect the results, so I'm quite curious. Thanks again.

**Comment by shunsukesaito** [comment]
We do not have a model trained with perspective projection. To incorporate perspective projection, you may need to train by yourself with perspective projection. Please refer to #29 for more info.
