### ISSUE TITLE
How to train this?

### ISSUE THREAD

**Issue by agnJason** [facebookresearch/pifuhd#35]
How to train this model? Can you provide code for training? And is there a public dataset that can train this model? Thank you!

**Comment by shunsukesaito** [comment]
Please refer to #29 for training information. As far as I know, there is no large-scale public dataset with high-quality details that PIFuHD enables to model. THUmanDataset provides wide range of clothed human but the geometric quality is not as good as commercial scans.
https://github.com/ZhengZerong/DeepHuman/tree/master/THUmanDataset
