### ISSUE TITLE
How to improve mesh accuracy

### ISSUE THREAD

**Issue by MolianWH** [facebookresearch/pifuhd#37]
Hi! Thanks for your great contribution.
I test a set of dance frames offline ( Use openpose body25 ), but the results are not so good as paper and sample given. My test result shows like that: 
**result**
<img src="https://user-images.githubusercontent.com/33748947/87680132-9fa7cd00-c7af-11ea-8150-c378d9dbf55a.png" width="200" />
![result_00200_512](https://user-images.githubusercontent.com/33748947/87680642-42604b80-c7b0-11ea-8316-b5b34de764ec.png)

Could you kindly offer some ideas about how to improve mesh  accuracy? Do I need  to train my own dataset of specified motion? How to deal with the noise?

Thanks.

**Comment by shunsukesaito** [comment]
Adding training data with larger pose variation alleviates this kind of failure mode. However it's not really feasible to cover all possible variation during training. So it's an interesting research topic on its own!!

**Comment by MolianWH** [comment]
@shunsukesaito  Thanks for your reply ! What could possibly cause noise in the background of the image below, even if the background is clean？
<img src="https://user-images.githubusercontent.com/33748947/87842776-c5cd8a00-c8e1-11ea-9975-f7796344f112.png" width="150"/>

**Comment by shunsukesaito** [comment]
Although it's difficult to accurately diagnose this particular case, my educated guess is the network might not be robust to block noise like JPEG artefacts as I did not add this kind of augmentation in the training.
