### ISSUE TITLE
CUDA Out of memory, even after changing default 

### ISSUE THREAD

**Issue by 7000gb** [facebookresearch/pifuhd#41]
After changing the default line:
**parser.add_argument('-r', '--resolution', type=int, default=100)**
from 512 to 100. I am still getting this error 

![image](https://user-images.githubusercontent.com/60055868/88242432-27338700-cc5b-11ea-9273-8b0d6cbe2694.png)

My GPU is Gtx 1060 6gb... Is there anyway to make the program more economical on my GPU?

**Comment by shunsukesaito** [comment]
AFAIK, the model cannot fit into 6GB no matter how you change the config. Potential workaround includes 1. use CPU only (#26 ) or 2. use Google colab demo (note that final resolution will be limited to 256).
