### ISSUE TITLE
1024 resolution

### ISSUE THREAD

**Issue by GuusDeKroon** [facebookresearch/pifuhd#42]
Hey,
I couldn't find any documentation on this. Is it possible? I tried using this command:

python -m apps.simple_test --resolution=1024

But it didn't give any output obj, and the output png only used the top left corner of the input image.
Thanks

**Comment by shunsukesaito** [comment]
Did you test it with the provided sample image or your own image? Please try out with the sample image and post the output png if it doesn't work. Otherwise, likely the input image doesn't have correct openpose file or rectangle file.
