### ISSUE TITLE
how do i run multiple images and video?

### ISSUE THREAD

**Issue by halog2609** [facebookresearch/pifuhd#43]
HI im trying to find a way to run multiple images and video would love for some help thank you

**Comment by shunsukesaito** [comment]
Images under the same folder will be all processed with the program. Please make sure you have "_keypoints.json" or "_rect.txt" for each image. If you want to process video data, you need to first extract frames using ffmpeg or opencv.

**Comment by hafenmeister** [comment]
How do i get the "_keypoints.json" for each image? And how should i name those images?
