### ISSUE TITLE
How to get a bigger model

### ISSUE THREAD

**Issue by jianghongsun** [facebookresearch/pifuhd#49]
hi，Thank you for sharing.
How to get a better model, a bigger model. Can you give me some advice，Thank you for your reply.

**Comment by shunsukesaito** [comment]
I'm not fully sure what you mean by "bigger" model. If you meant supporting larger input image, as long as it can fit into GPU memory, the PIFuHD framework can be applied to even higher resolution. Regarding a better model, this itself is an interesting open research question.

**Comment by jianghongsun** [comment]
Thank you for your reply. What I want to express is that at present, if the size of the input image is m * n, input it into the network to generate the model of m * n picture. It seems that the model is generated only when the m * n image is input and the image size is 512 * 512 . I don't know if I understand it wrong,and how to relize this function. Thank you for your reply.

**Comment by shunsukesaito** [comment]
The released model is trained with the fixed input image resolution and thus best performing with the exact same setting. If you want to try without resizing to 1024x1024, you need to train a new model with the resolution you want.
