### ISSUE TITLE
Issues about the inputs of HGPIFuMRNet

### ISSUE THREAD

**Issue by troylujc** [facebookresearch/pifuhd#51]
When I read the code of HGPIFuMRNet.py, I'm not clear about the meaning of _images_local_([B1, B2, C, H, W]) and _images_global_([B1, C, H, W]). What is the difference between _images_local_ and _images_global_ and what does _B1, B2_ mean?
And for _points_nml_ and _labels_nml_, are they from .obj file or calculated?
@shunsukesaito Thank you!

**Comment by shunsukesaito** [comment]
> What is the difference between images_local and images_global and what does B1, B2 mean?

images_global corresponds to the input for the coarse PIFu module and images_local to the fine PIFu module. Regarding B1/B2, during evaluation, B2 is always 1. During training, images_local are not the whole image (1024 x 1024), but local cropping (512 x 512). B2 allows us to take multiple cropping from the same image.

> And for points_nml and labels_nml, are they from .obj file or calculated?

For the ground truth, yes we calculated from the original input file. But these labels are computed from pix2pixhd inference of surface normal in the image space. Please refer to the paper for more details.

**Comment by troylujc** [comment]
> > What is the difference between images_local and images_global and what does B1, B2 mean?
> 
> images_global corresponds to the input for the coarse PIFu module and images_local to the fine PIFu module. Regarding B1/B2, during evaluation, B2 is always 1. During training, images_local are not the whole image (1024 x 1024), but local cropping (512 x 512). B2 allows us to take multiple cropping from the same image.
> 
> > And for points_nml and labels_nml, are they from .obj file or calculated?
> 
> For the ground truth, yes we calculated from the original input file. But these labels are computed from pix2pixhd inference of surface normal in the image space. Please refer to the paper for more details.

Thank you for your kind reply!
I have another question. During training, is the local cropping finished randomly with overlapping _images_local_ or just cropping whole image from 1024*1024 to 4 512*512 images? And if it is finished randomly, what is the proper B2 number?

**Comment by shunsukesaito** [comment]
The selection of cropping window is completely random (note that this cropping is applied only during training, and the whole image (1024x1024) is fed into the network during inference.) I tried various numbers but reconstruction accuracy is insensitive to the choice of B2. I ended up using B2 = 2, but can be any numbers as long as it can fit into your GPU memory.

**Comment by troylujc** [comment]
> > What is the difference between images_local and images_global and what does B1, B2 mean?
> 
> images_global corresponds to the input for the coarse PIFu module and images_local to the fine PIFu module. Regarding B1/B2, during evaluation, B2 is always 1. During training, images_local are not the whole image (1024 x 1024), but local cropping (512 x 512). B2 allows us to take multiple cropping from the same image.
> 
> > And for points_nml and labels_nml, are they from .obj file or calculated?
> 
> For the ground truth, yes we calculated from the original input file. But these labels are computed from pix2pixhd inference of surface normal in the image space. Please refer to the paper for more details.

When I try to train pifuhd, in the code HGPIFuMRNet.py line 102, it upsample _nmls_ to _loadSizeBig_ (I think is 1024 * 1024), and cat _nmls_ with _images_local_ (I think is 512 * 512), where the size does not match. Is there something I'm wrong?

**Comment by troylujc** [comment]
> The input normal and images_local should be using the same cropping to achieve pixel-aligned reconstruction. So make sure your input normal is cropped in the same way as images_local.

Thank you for your reply.  Now I cropped normal in the same way as images_local. But the training result seems still have some problem. The prediction has mistakes in depth, and there are many false positive points outside the body area. Is there any potential reason you could think of?
![image](https://user-images.githubusercontent.com/29535232/91003631-70814880-e604-11ea-949a-eeb4535c3d53.png)
![image](https://user-images.githubusercontent.com/29535232/91003655-80009180-e604-11ea-8d68-045fadfa6238.png)
