### ISSUE TITLE
cuda out of memory when training with 24G  gpu memory 

### ISSUE THREAD

**Issue by SFM2020** [facebookresearch/pifuhd#53]
The number of network parameters of PIFuHD is 387 million,which is 25 times that of PIFu.  Can you share with us the hardware requirements of your GPU  when training pifuhd?  Such as GPU memory, type and number of gpus.The GPU memory I used for training was 24g,batch_size=1, but still cuda out of memory

**Comment by shunsukesaito** [comment]
I suppose you are trying to train the fine module with the entire image (1024x1024). Yes, this model is not feasible to train with the full resolution as it is. The trick is to randomly crop 512x512 images from the original input and supervise within the cropped region. The full resolution image is fed only during inference.

**Comment by SFM2020** [comment]
yeah,you are right！now I can train them  after crop images .really appreciate !

**Comment by tejokrishna** [comment]
@SFM2020 were able to train with crops? If so can you share the learning rate you used?

**Comment by tryingeverday** [comment]
> @SFM2020 were able to train with crops? If so can you share the learning rate you used?

I’m an idiot and I keep getting the output “cuda out of memory”  I’m not sure how to train with crops but I would be very happy if you could explain if you have a moment please.
