### ISSUE TITLE
Access Voxel Data

### ISSUE THREAD

**Issue by FeiYin99** [facebookresearch/pifuhd#56]
Is there a way to access the data of every voxel from the reconstruction, for example, each voxel's depth and sdf value?

**Comment by shunsukesaito** [comment]
here you go.
https://github.com/facebookresearch/pifuhd/blob/a1559aee7f5e8584c94a74b50be29306481f4e06/lib/mesh_util.py#L71

**Comment by shunsukesaito** [comment]
Please be aware that the value is occupancy probability not actual signed distance fields (it's named sdf though).

**Comment by FeiYin99** [comment]
Thanks for the quick reply. I will look into that.
