### ISSUE TITLE
the piFuHd file is gone in the google drive

### ISSUE THREAD

**Issue by andrewyau41** [facebookresearch/pifuhd#58]
Help !!!!!!!!!!!!!!!!!!!!!!!!!!!

the pifuhd file is gone in the google drive demo. 

Can't find the pifuhd file to input the images in

**Comment by shunsukesaito** [comment]
Please follow the colab lines one by one. In the beginning, you are not supposed to see pifuhd folder, so nothing is wrong in your case.
