### ISSUE TITLE
test.sh is not creating the mask ?

### ISSUE THREAD

**Issue by Ulf3000** [facebookresearch/pifuhd#59]
./sample_images\127503458.jpg ./sample_images\127503458_mask.png
error: (2, 'No such file or directory')

somehow it doesnt process my image corrctly , can i create the mask by some code or can i make it myself in photoshop ?

**Comment by shunsukesaito** [comment]
test.sh does not create mask fine as pifuhd does not require segmentation.

**Comment by Ulf3000** [comment]
sorry i extracted pifu into pifuhd folder .
