### ISSUE TITLE
How to improve the reconstruction quality? 

### ISSUE THREAD

**Issue by layumi** [facebookresearch/pifuhd#60]
Dear author, 

Thanks a lot for your great code. I have successfully deployed the open-pose and your code to reconstruct my own data.
But the reconstruction quality is not very good. 
The result is as the following figures. I am not sure whether it is normal. Is it due to the domain gap?  
Do you have any suggestions? My input data is 256 x 128. 
Thanks a lot! 

![image](https://user-images.githubusercontent.com/8390471/91294009-38346280-e7dc-11ea-9638-7defbaaa06f5.png)
![image](https://user-images.githubusercontent.com/8390471/91294044-45e9e800-e7dc-11ea-8bb6-8495e51a7d71.png)

**Comment by shunsukesaito** [comment]
As the primary focus of the work is to reconstruct highly detailed 3d geometry from 1k resolution images. our model performs best with these high-res images (and that's how I trained the model).

**Comment by zener90818** [comment]
@layumi Hi， Could you share the training code， thanks a lot
