### ISSUE TITLE
自分の3Dメッシュデータを使って学習はできないのでしょうか

### ISSUE THREAD

**Issue by momizi123** [facebookresearch/pifuhd#61]
今現在pifuhdを自分のPCで触らせてもらっています。
質問なのですがこれは私のもっている3Dメッシュデータを学習させることはできないのでしょうか。
readmeとコードを見る限りはなさそうなのですが一応質問させてもらいました。

**Comment by shunsukesaito** [comment]
Please refer to #29 as it has been discussed by other users as well.

**Comment by momizi123** [comment]
thank you!!

**Comment by momizi123** [comment]
#29を見させてもらい、現在pifuのtrain_shapeとTrainDatasetに変更を加えています。
しかし、何度試してもうまくいきません。必須のコマンドラインオプションなどがありましたら教えて頂けないでしょうか。
