### ISSUE TITLE
ImportError: cannot import name 'Textures'

### ISSUE THREAD

**Issue by ak9250** [facebookresearch/pifuhd#64]
ImportError                               Traceback (most recent call last)
<ipython-input-6-22614b7ef849> in <module>()
----> 1 from lib.colab_util import generate_video_from_obj, set_renderer, video
      2 
      3 renderer = set_renderer()
      4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
      5 

/content/pifuhd/lib/colab_util.py in <module>()
     39 
     40 # Data structures and functions for rendering
---> 41 from pytorch3d.structures import Meshes, Textures
     42 from pytorch3d.renderer import (
     43     look_at_view_transform,

ImportError: cannot import name 'Textures'

from the google colab could be due to pytorch3d version?

**Comment by shunsukesaito** [comment]
The same issue was raised in PIFu repository and the pull request is merged there. Unfortunately I don't have bandwidth to change the code in PIFuHD for now. But you can make the same modification in pifuhd repo as well. Thanks.
https://github.com/shunsukesaito/PIFu/issues/66

**Comment by suyashjoshi** [comment]
I'm seeing same error, very annoying.

**Comment by suyashjoshi** [comment]
> The same issue was raised in PIFu repository and the pull request is merged there. Unfortunately I don't have bandwidth to change the code in PIFuHD for now. But you can make the same modification in pifuhd repo as well. Thanks.
> [shunsukesaito/PIFu#66](https://github.com/shunsukesaito/PIFu/issues/66)

after making the suggested change, still getting another error:

```
/content/pifuhd/lib/colab_util.py in <module>()
     41 from pytorch3d.renderer import TexturesVertex
     42 from pytorch3d.structures import Meshes
---> 43 from pytorch3d.renderer import (
     44     look_at_view_transform,
     45     OpenGLOrthographicCameras,

ImportError: cannot import name 'TexturedSoftPhongShader'

```

**Comment by hfarhidzadeh** [comment]
Facing same issue :/

**Comment by GambleV** [comment]
Same issue
PyTorch3D is updated to v 0.2.5 (https://github.com/facebookresearch/pytorch3d/releases)
Now, `from pytorch3d.structures import Textures` --> 
`from pytorch3d.renderer import TexturesUV, TexturesVertex, TexturesAtlas`

Line 42
`from pytorch3d.renderer import (
    look_at_view_transform,
    OpenGLOrthographicCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    TexturedSoftPhongShader,
    HardPhongShader
)`
to
`from pytorch3d.renderer import (
    look_at_view_transform,
    OpenGLOrthographicCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    HardPhongShader,
    TexturesUV,
    TexturesVertex,
    TexturesAtlas
)`

Line 111
`textures = Textures(verts_rgb=verts_rgb_colors)
    wo_textures = Textures(verts_rgb=torch.ones_like(verts_rgb_colors)*0.75)`
to
` textures = TexturesVertex(verts_rgb=verts_rgb_colors)
   wo_textures = TexturesVertex(verts_rgb=torch.ones_like(verts_rgb_colors)*0.75)`

After that,it work :)

**Comment by farazBhatti** [comment]
@GambleV  after applying chagnges you recommended above, I am getting the following error.

```
    114     verts_rgb_colors = get_verts_rgb_colors(obj_path)
    115     verts_rgb_colors = torch.from_numpy(verts_rgb_colors).to(device)
--> 116     textures = TexturesVertex(verts_rgb=verts_rgb_colors)
    117     wo_textures = TexturesVertex(verts_rgb=torch.ones_like(verts_rgb_colors)*0.75)
    118 

TypeError: __init__() got an unexpected keyword argument 'verts_rgb'

```
Any help? Thanks

**Comment by GambleV** [comment]
@farazBhatti , apologize for post wrong ans. The two lines should be changed to
`textures = TexturesVertex(verts_features=verts_rgb_colors)`
`wo_textures = TexturesVertex(verts_features=torch.ones_like(verts_rgb_colors)*0.75)`
 
Try this :)

**Comment by wanfuse123** [comment]
where in the google colab do I put this?

Thanks!!!

**Comment by wanfuse123** [comment]
Also, Do you have detailed instructions for running this locally? Or in a docker VM (with and without nvidai-cuda support?)

**Comment by GambleV** [comment]
@wanfuse123 
git+url ?
I just test it in google colab for PIFuHD example.

**Comment by wanfuse123** [comment]
What FILE is this change supposed to be made in ? I downloaded the project , installed all its dependencies, and I get the error. Can you tell me what file these lines are changed in. 

grep -R "from pytorch3d.renderer import" . turns up nothing in the pifudh directory.


Thanks for being patient!

**Comment by EnricoBeltramo** [comment]
for me error at:

NameError                                 Traceback (most recent call last)
<ipython-input-22-22614b7ef849> in <module>()
      2 
      3 renderer = set_renderer()
----> 4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
      5 
      6 # we cannot play a mp4 video generated by cv2

/content/pifuhd/lib/colab_util.py in generate_video_from_obj(obj_path, image_path, video_path, renderer)
    106     f rom pytorch3d.renderer import Meshes
    107     vers = mesh._verts_list
--> 108     faces = mesh._faces_list
    109     mesh_w_tex = Meshes(vers, faces, textures)
    110     mesh_wo_tex = Meshes(vers, faces, wo_textures)

NameError: name 'Meshes' is not defined

**Comment by GambleV** [comment]
@EnricoBeltramo 
Line 106
Try `from pytorch3d.structures import Meshes `

**Comment by GambleV** [comment]
This issue occur in lib/colab_util.py when use `from pytorch3d.structures import Textures`. But new version `Textures` is deprecated.

**Comment by EnricoBeltramo** [comment]
> @EnricoBeltramo
> Line 106
> Try `from pytorch3d.structures import Meshes `

I suppose meshes doesn't exist anymore in pytorch3d:

---> 41 from pytorch3d.renderer import TexturesUV, TexturesVertex, TexturesAtlas, Meshes
     42 from pytorch3d.renderer import ( look_at_view_transform, OpenGLOrthographicCameras, PointLights, DirectionalLights, Materials, RasterizationSettings, MeshRenderer, MeshRasterizer, SoftPhongShader, HardPhongShader, TexturesUV, TexturesVertex, TexturesAtlas )
     43 

ImportError: cannot import name 'Meshes'

Some one know the correct version of pytorch3d in order to change colab here:
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
and align to version of pytorch3d  the SW was tested with?

**Comment by shunsukesaito** [comment]
Sorry for having you guys wait for long time. I just made fix and it should be working now!
