### ISSUE TITLE
Results of Model Creation -Distortion in the Z axis

### ISSUE THREAD

**Issue by wanfuse123** [facebookresearch/pifuhd#67]
I am wondering, is there a way to get this to work with multiple perspective views, basically video of 360 around a model. There is terrible distortion in the Z axis.

Thanks in advance for your time!
https://gofile.io/d/XZhX9a << object file example

**Comment by shunsukesaito** [comment]
This is in fact a really interesting research question and I don't think it has been fully resolved by any methods yet.
