### ISSUE TITLE
How to implement texture prediction based on PIFuhd, like PIFu?

### ISSUE THREAD

**Issue by zhouliuling** [facebookresearch/pifuhd#68]
How to implement texture prediction based on PIFuhd, like PIFu?
Thank you very much for your research. Compared with PIFu, the reconstruction accuracy of PIFuHD is greatly improved, but the prediction of texture is not included.As far as I know, the texture prediction network and the surface reconstruction network of PIFu project are separated. How to realize the texture prediction based on the surface reconstruction of PIFuHD?I hope you can give guidance.

**Comment by shunsukesaito** [comment]
The texture prediction module in PIFu can be directly used in PIFuHD pipeline as well (it requires modifying the current code slightly though). In this repository, we do not plan to add such a functionality at this moment.
