### ISSUE TITLE
it is work that "any png  replace  test.png" ?????

### ISSUE THREAD

**Issue by jinpengchina** [facebookresearch/pifuhd#7]
i try other png,  it is not work

**Comment by jinpengchina** [comment]
> i try other png, it is not work

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-261-22614b7ef849> in <module>()
      2 
      3 renderer = set_renderer()
----> 4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
      5 
      6 # we cannot play a mp4 video generated by cv2

/content/pifuhd/lib/colab_util.py in generate_video_from_obj(obj_path, image_path, video_path, renderer)
     99 def generate_video_from_obj(obj_path, image_path, video_path, renderer):
    100     input_image = cv2.imread(image_path)
--> 101     input_image = input_image[:,:input_image.shape[1]//3]
    102     input_image = cv2.resize(input_image, (512,512))
    103 

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by carlosedubarreto** [comment]
Check the folder of the file. I had this problem, and the error was similar to this one.
Conectado 15/06/2020 10:53:34, jinpengchina <notifications@github.com> escreveu:
i try other png, it is not work
AttributeError Traceback (most recent call last)
in ()
2
3 renderer = set_renderer()
----> 4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
5
6 # we cannot play a mp4 video generated by cv2
/content/pifuhd/lib/colab_util.py in generate_video_from_obj(obj_path, image_path, video_path, renderer)
99 def generate_video_from_obj(obj_path, image_path, video_path, renderer):
100 input_image = cv2.imread(image_path)
--> 101 input_image = input_image[:,:input_image.shape[1]//3]
102 input_image = cv2.resize(input_image, (512,512))
103
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by jinpengchina** [comment]
"test_keypoints.json"  ,   how to generate this file ????

this project will not work without it!!!!

**Comment by gormonn** [comment]
> "test_keypoints.json" , how to generate this file ????
> 
> this project will not work without it!!!!

You need Openpose to get this file. Check Readme.

**Comment by shunsukesaito** [comment]
Alternatively the code supports bounding box file named '{file_name}_rect.txt", containing (left, top, width, height). The colab demo provides light-weight code to get these bounding box files.

https://colab.research.google.com/drive/11z58bl3meSzo6kFqkahMa35G5jmh2Wgt

**Comment by jeesunkim** [comment]
@gormonn You need the test_keypoints.json file...
If you are on windows:
install openpose demo
put your test file in a folder under the Openpose roor, e.g., examples\media\test.png
open a powershell or cmd window in the Openpose root
bin\OpenPoseDemo.exe --image_dir examples\media\test.png --face --hand --write_json output/
The above will create a json file - put that and your test image in the pifuhd/sample_images folder
then it should create an obj in the results\pifuhd_final\recon folder

**Comment by jeesunkim** [comment]
Openpose portable version for windows here - https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases
Select openpose-1.6.0-binaries-win64-gpu-python-flir-3d_recommended.zip (if you have a gpu)
Unzip 
Now put your test png file in a folder under the Openpose root directory, e.g., examples\media\test.png - make sure it is the only png file in that folder
then open a windows command window - and naviagate to the openpose root dir and issue this command
 bin\OpenPoseDemo.exe --image_dir examples\media\test.png --face --hand --write_json output/
This will create a test_keypoints.json file - this is what you use with pifuhd...

**Comment by shunsukesaito** [comment]
Please take a look at #12.

**Comment by rdelrosa2000** [comment]
Hi. The program initially worked for me but now I’m also getting an AttributeError message.  What could be the problem?  Please help.
