### ISSUE TITLE
this can be trained with faces, and generate 3d head from a single photo?

### ISSUE THREAD

**Issue by molo32** [facebookresearch/pifuhd#71]
this can be trained with faces, and generate 3d head from a single photo?

can I train with anything in 2d, to convert it to 3d?

**Comment by shunsukesaito** [comment]
Yes it's certainly doable. You can retrain a model by replacing the RenderPeople data with some 3d head datasets.

**Comment by AKclown** [comment]
Hi, how do I train the head model? Too little relevant information makes me unable to start

**Comment by AKclown** [comment]
@molo32  Did you solve it?
