### ISSUE TITLE
Input image rotating 90 degrees anti-clockwise

### ISSUE THREAD

**Issue by durgesh17media** [facebookresearch/pifuhd#72]
My input image is rotating 90 degrees anti-clockwise when giving as input that's why mesh is also distorted. Kindly help with the same. @shunsukesaito 
![lakshmi](https://user-images.githubusercontent.com/65701365/96446258-ce11ca00-122e-11eb-8535-6d94d20b4ab4.jpg)

**Comment by durgesh17media** [comment]
![lakshmi](https://user-images.githubusercontent.com/65701365/96446225-be928100-122e-11eb-96b1-320216be17fe.jpg)

**Comment by shunsukesaito** [comment]
Probably this stackoverflow is relevant. 

https://stackoverflow.com/questions/10600613/ios-image-orientation-has-strange-behavior#:~:text=Any%20image%20generated%20by%20iPhone,Orientation)%20specifying%20the%20actual%20orientation.&text=In%20IOS%2C%20the%20EXIF%20info,same%20way%20it%20was%20taken.

**Comment by Tanupvats** [comment]
I run into the same problem but there was an issue mentioned about the image metadata try to remove it and resize your image to 1024X1024. if you still don't get the results then remove the background of the image in which the person is standing and then feed it in the model. it worked for me though.
