### ISSUE TITLE
how to calculate metrics for BUFF with 2D images.

### ISSUE THREAD

**Issue by pursur** [facebookresearch/pifuhd#73]
I have known BUFF is only used  for evaluation. However, as far as I know, this dataset has only 3D ply files and no 2D images. Without 2D images, the reconstructed mesh files should not be able to get  via the code, which is also unable to compare with the original ply files.

**Comment by shunsukesaito** [comment]
We synthetically render the BUFF data with the same camera configuration as RenderPeople. The rendering code is available in the PIFu repository. 
https://github.com/shunsukesaito/PIFu

**Comment by pursur** [comment]
yes, I have achieved the rendering code(render_data.py) using the renderpeople dataset. However,it seems that diffuse mapping is required for rendering in render_data.py. There is no diffuse mapping in  the BUFF dataset. Where can I generate  diffuse mappings. Is it OpenGL or other ways?

**Comment by shunsukesaito** [comment]
BUFF texture already contains some shading thus no additional diffuse shading is required. You can render the per-vertex color as it is.
