### ISSUE TITLE
No module named apps.simple_test

### ISSUE THREAD

**Issue by elduend3** [facebookresearch/pifuhd#75]
Hi all, 

First I wasn't able to visualize apps module, but then I corrected the python version, so I am not receiving issues when importing apps.

This is the current python version I have:

**$ python --version**
Python 3.8.5

But when I try to execute this, I receive that error:

**$ sh ./scripts/demo.sh**
/usr/bin/python: No module named apps.simple_test
/usr/bin/python: No module named apps.render_turntable

Or just that line:
**$ python -m apps.simple_test**
/usr/bin/python: No module named apps.simple_test

Do you know if my apps module is not imported/installed correctly?

**Comment by chiru-stefan** [comment]
there are a few steps that you have to follow before running the demo.sh
First export the path to the 'apps'. if you are using Linux, this can be done by running the following from inside the pifuhd directory:
`export PYTHONPATH=$(pwd):$PYTHONPATH ; export PYTHONPATH=$(pwd)/apps:$PYTHONPATH ; export PYTHONPATH=$(pwd)/scripts:$PYTHONPATH`
activate the virtual env (to create a virtual env ---> python3 -m venv pifuhd-venv; source pifuhd-venv/bin/activate; pip install --upgrade pip; pip install --upgrade setuptools; pip install -r requirements.txt)
cd scripts
bash demo.sh

**Comment by shankch** [comment]
how to do this in windows , i am getting the same error, "Error while finding module specification for 'apps.simple_test' (ModuleNotFoundError: No module named 'apps')"

**Comment by IamVulgar** [comment]
Guess he doesn't care to help out us windows folk.
