### ISSUE TITLE
Rendering error with pytorch3d in Google colab demo 

### ISSUE THREAD

**Issue by ShivamSRS** [facebookresearch/pifuhd#76]
**What I did :**

Ran colab demo mentioned on the website https://shunsukesaito.github.io/PIFuHD/
tried both with an image uploaded by me and the default test image mentioned in the notebook, both gave same error since it is an import error

**lines that give error :** 
from lib.colab_util import generate_video_from_obj, set_renderer, video

**error traceback :**

ImportError                               Traceback (most recent call last)
<ipython-input-34-22614b7ef849> in <module>()
----> 1 from lib.colab_util import generate_video_from_obj, set_renderer, video
      2 
      3 renderer = set_renderer()
      4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
      5 

4 frames
/usr/local/lib/python3.6/dist-packages/pytorch3d/renderer/blending.py in <module>()
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

Maybe the _C module got moved in pytorch 3d?

**Comment by shunsukesaito** [comment]
Please refer to #77
