### ISSUE TITLE
Can we get an output with lesser polycount (tricount)?

### ISSUE THREAD

**Issue by trivikramak** [facebookresearch/pifuhd#86]
I have tried to generate a character model from an image and got a sculpt from it (tri-count of around 500,000). Can we achieve an output with similar level of details but having lower tri-count (around 30k) without having to manually re-topologize? It would be useful to get outputs with lower tri-count even if a few of the details are compromised.

**Comment by shunsukesaito** [comment]
You can post-process the resulting meshes with existing decimation algorithms. Opensourced softwares such as Blender and meshlab has a functionality for it.
