### ISSUE TITLE
color mesh is weird

### ISSUE THREAD

**Issue by name8997** [facebookresearch/pifuhd#9]
Thank you for your great work

but i have a trouble with getting color mesh

I changed from get_mesh to get_mesh_img on recon.py and executed. The result is the same on the front and back as in the picture below. Is there any additional part that I need to set up?

Thank you

![Untitled](https://user-images.githubusercontent.com/42572607/84746229-a3013a80-aff0-11ea-98a1-69e4a0e30475.png)
![Untitled (1)](https://user-images.githubusercontent.com/42572607/84746236-a5639480-aff0-11ea-8889-a787cc691142.png)

**Comment by shunsukesaito** [comment]
As the pretrained model only provides geometry inference, get_mesh_img simply projects input image onto mesh. We don't have texture inference module as in the original PIFu. So this is the expected result.

**Comment by FrankEscobar** [comment]
Oh that's a pitty! I could be really nice if it could also guess the texture as the original Pifu

**Comment by name8997** [comment]
thank you for reply! 
I will find other ways

**Comment by ReeseL** [comment]
> As the pretrained model only provides geometry inference, get_mesh_img simply projects input image onto mesh. We don't have texture inference module as in the original PIFu. So this is the expected result.
@shunsukesaito 
the model from pifuhd could be used in texture inference module from the original pifu ?

**Comment by shunsukesaito** [comment]
As the latent feature of PIFuHD is not compatible with original PIFu, only way would be to use texture inference model with the original PIFu geometry but evaluate points of PIFuHD reconstruction. If PIFu reconstruction and PIFuHD reconstruction are close enough, that might give you satisfactory results.

**Comment by ReeseL** [comment]
thank you for reply!
