### ISSUE TITLE
Google Colab demo not working: Could not find name `_C` in `pytorch3d`.

### ISSUE THREAD

**Issue by ourii** [facebookresearch/pifuhd#92]
I am running the sample code on GOogle Colab without any modfications but I get the following error when trying to run
`from lib.colab_util import generate_video_from_obj, set_renderer, video`:

ImportError                               Traceback (most recent call last)
<ipython-input-24-22614b7ef849> in <module>()
----> 1 from lib.colab_util import generate_video_from_obj, set_renderer, video
      2 
      3 renderer = set_renderer()
      4 generate_video_from_obj(obj_path, out_img_path, video_path, renderer)
      5 

4 frames
/usr/local/lib/python3.6/dist-packages/pytorch3d/renderer/blending.py in <module>()
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

Why is this happening? How can I solve it?
I guess all Colab users should be getting the same issue...

Thanks

**Comment by ultrafez** [comment]
I've had the same issue - exact same stack trace and error message.

It's been a while since I've used Python in anger, but pytorch3d version 0.3.0 was released 9 days ago, so I tried forcing it to install the previous version with `!pip install 'pytorch3d=0.2.5'` but that didn't help - same error.

**Comment by rbritten** [comment]
Fix is here: https://github.com/facebookresearch/pifuhd/issues/77#issuecomment-725247401
