### ISSUE TITLE
Is there anyway to transform pifuhd's result to SMPL's params?

### ISSUE THREAD

**Issue by hot-dog** [facebookresearch/pifuhd#95]
I want to animate a single image and i am wondering is it possible to get SMPL's params from the output of pifuhd? If it can, then how? Any reply is welcomed, thank you!

**Comment by jhugestar** [comment]
This would be a relevant solution:

https://www.youtube.com/watch?v=DG3QNMcmTvo

I guess it's not open-sourced, though.

**Comment by hot-dog** [comment]
Thanks for your reply, i will check it.
