### ISSUE TITLE
Including original image as texture

### ISSUE THREAD

**Issue by stevesmit** [facebookresearch/pifuhd#99]
In the paper, I note in figure 2 that the original image appears to have been placed on the mesh. Is this possible with the code in this repo? If so, could you point me in the right direction?

**Comment by shunsukesaito** [comment]
The resulting meshes are in the pixel coordinates after cropping. So if you render the meshes with orthogonal projection, you can overlay the rendering on the input image as in Fig. 2. Currently no plan to release this rendering code itself in the repo.

**Comment by merlinyx** [comment]
Hi! I've been trying to do the orthogonal projection based on the camera paramters in camera.py, or through reverting the reconstruction process to get back to the pixel coordinates but the resulting projection does not align with the input image (meaning if I project the pifuhd output onto the input image coordinate space, the points do not fall on the human in the image and the scale is a bit off). Do you know what might be the issue? Was there any hidden or default transformation to make them align? Thank you!
